# Data Preprocessing
Preprocess `cross_references.tsv` according to the initial EDA.

In [1]:
import pandas as pd

In [2]:
raw_data = pd.read_csv('data/original_data/cross_references.tsv', sep='\t')
raw_data.sample(10)

,From Verse,To Verse,Votes,#www.openbible.info CC-BY 2026-09-07
247368,Mark.9.41,1Cor.15.23,0,NaN
121690,Ps.63.1,1Sam.23.23-1Sam.23.25,9,NaN
3870,Gen.16.12,Gen.25.18,8,NaN
160507,Isa.25.4,Ezek.13.11-Ezek.13.13,2,NaN
244317,Mark.1.39,Mark.1.21,3,NaN
21315,Exod.32.1,Josh.7.13,3,NaN
34367,Num.18.16,Ezek.45.12,3,NaN
329229,Heb.13.5,Isa.41.17,84,NaN
146110,Prov.20.22,1Pet.3.9,101,NaN
306190,Gal.2.9,1John.1.3,3,NaN

In [3]:
data = raw_data.iloc[:,0:3]
display(data.shape)
display(data.sample(5))

(344756, 3)

       From Verse         To Verse  Votes
339028   Rev.2.21  Jer.8.4-Jer.8.6      4
157066  Isa.10.12         Dan.4.37      3
30908    Num.3.47       Exod.30.13      5
319900  1Tim.3.16          Heb.1.3     40
319820  1Tim.3.15        2Cor.6.16      3

In [4]:
# remove negative and zero votes
data_positive = data.loc[data['Votes']>0]
display(data_positive.shape)
display(data_positive.sample(5))

(341242, 3)

         From Verse              To Verse  Votes
184877    Jer.30.21            Deut.18.18      6
316918  1Thess.3.10               Rev.4.8      2
186716     Jer.34.7  2Chr.11.5-2Chr.11.10      3
337671    3John.1.5            Luke.12.42      4
92479     2Chr.34.9             2Kgs.23.4      2

In [5]:
def filter_func(row, max_verse):
    # identify if the from verse and to verse are from the same chapter
    chap1 = '.'.join(row['From Verse'].split('.')[:2])
    chap2 = '.'.join(row['To Verse'].split('.')[:2])
    same_chapter = chap1 == chap2

    # if the To Verse spans multiple verses:
    if '-' in row['To Verse']:
        # Check whether it spans multiple chapters
        start, end = row['To Verse'].split('-')
        start_parts = start.split('.')
        end_parts = end.split('.')

        # check whether 'To Verse' stays within one chapter
        not_multi_chapter = start_parts[:2] == end_parts[:2]
        
        # check the number of verses it spans
        start_verse = int(start_parts[2])
        end_verse = int(end_parts[2])
        verse_span = end_verse - start_verse + 1
    else:
        not_multi_chapter = True
        verse_span = 1
    return (not same_chapter) and not_multi_chapter and (verse_span <= max_verse)

In [6]:
# Apply filter
idx_filter = data_positive.apply(filter_func, max_verse=5, axis=1) # set max verse span to 5
data_filtered = data_positive.loc[idx_filter, :]
display(data_filtered.shape)
display(data_filtered.sample(10))

(312791, 3)

        From Verse             To Verse  Votes
15033    Exod.8.12           Ezek.36.37      5
290116    Rom.4.19  Mark.9.23-Mark.9.24      4
109517      Ps.5.6             Ps.55.23      9
249309  Mark.14.13              Heb.5.9      1
210863    Dan.7.13             Rev.1.18     17
70961   1Kgs.11.43            2Chr.9.31      2
89406    2Chr.19.3             Rom.7.18      2
289226    Rom.2.27            Matt.3.15      2
146593   Prov.22.5  Jude.1.20-Jude.1.21      5
178764   Jer.11.20              Ps.98.9      3

In [11]:
# save filtered data
data_filtered.to_csv('data/data_filtered.tsv', sep='\t')