# Data Preprocessing
Preprocess `cross_references.tsv` according to the initial EDA.

In [2]:
import pandas as pd

In [3]:
raw_data = pd.read_csv('cross_references.tsv', sep='\t')
raw_data.sample(10)

,From Verse,To Verse,Votes,#www.openbible.info CC-BY 2026-09-07
287103,Acts.26.18,1John.3.8,14,NaN
283831,Acts.17.31,2Tim.4.1,3,NaN
110446,Ps.9.18,Ps.72.12-Ps.72.14,2,NaN
165752,Isa.41.11,Isa.60.12-Isa.60.14,6,NaN
312468,Phil.2.10,Rom.11.4,1,NaN
176496,Jer.5.31,Ezek.13.6,9,NaN
138605,Ps.143.7,Ps.88.10-Ps.88.11,3,NaN
266465,John.6.61,Rev.2.23,3,NaN
233463,Matt.7.21,Acts.14.22,11,NaN
110607,Ps.10.7,Job.15.35,2,NaN

In [4]:
data = raw_data.iloc[:,0:3]
display(data.shape)
display(data.sample(5))

(344756, 3)

        From Verse               To Verse  Votes
190677   Jer.49.31              Zeph.2.15      2
224165   Zeph.2.11              Zech.13.2      4
273925  John.19.32  Luke.23.39-Luke.23.43      1
193974    Lam.3.40    Job.11.13-Job.11.15      6
216888   Joel.2.21     Jer.30.9-Jer.30.10      8

In [5]:
# remove negative and zero votes
data_positive = data.loc[data['Votes']>0]
display(data_positive.shape)
display(data_positive.sample(5))

(341242, 3)

       From Verse             To Verse  Votes
113057   Ps.22.12            Matt.27.1      9
245946  Mark.6.18  Matt.14.3-Matt.14.4      2
254793  Luke.8.24              Ps.65.7      4
212841   Dan.12.4            Rom.10.18      7
259977  Luke.19.4            Amos.7.14      3

In [9]:
def filter_func(row, max_verse):
    # identify if the from verse and to verse are from the same chapter
    chap1 = '.'.join(row['From Verse'].split('.')[:2])
    chap2 = '.'.join(row['To Verse'].split('.')[:2])
    same_chapter = chap1 == chap2

    # if the To Verse spans multiple verses:
    if '-' in row['To Verse']:
        # Check whether it spans multiple chapters
        start, end = row['To Verse'].split('-')
        start_parts = start.split('.')
        end_parts = end.split('.')

        # check whether 'To Verse' stays within one chapter
        not_multi_chapter = start_parts[:2] == end_parts[:2]
        
        # check the number of verses it spans
        start_verse = int(start_parts[2])
        end_verse = int(end_parts[2])
        verse_span = end_verse - start_verse + 1
    else:
        not_multi_chapter = True
        verse_span = 1
    return (not same_chapter) and not_multi_chapter and (verse_span <= max_verse)

In [10]:
# Apply filter
idx_filter = data_positive.apply(filter_func, max_verse=5, axis=1) # set max verse span to 5
data_filtered = data_positive.loc[idx_filter, :]
display(data_filtered.shape)
display(data_filtered.sample(10))

(312791, 3)

        From Verse             To Verse  Votes
274759    Acts.1.6             Isa.1.26      3
155212     Isa.4.5    Isa.31.4-Isa.31.5      2
233397   Matt.7.16             Jas.3.12     21
215052     Hos.9.8             Jer.31.6      2
169238   Isa.49.25            Isa.10.27     29
145032  Prov.17.13  Jer.18.20-Jer.18.21      5
212440   Dan.11.21             Dan.8.25      3
214854    Hos.8.13            Jer.14.10      3
98576     Esth.4.3           Matt.22.13      2
152696   Song.2.11  Rev.11.14-Rev.11.15      2

In [11]:
# save filtered data
data_filtered.to_csv('data_filtered.tsv', sep='\t')